完善了 #63 中的建议
heyblog/V2 pull request #69
Opened 2022-05-05 13:55 UTC by Redish101

删除几个字段：博客头像，联系邮箱，网站架构。
修改隐藏栏为未审核栏。
更改展示滑块为审核通过按钮。
详情请查看 #63

2022-05-05 14:55 UTC, OhYee commented
字段等讨论结果再确定要不要删除吧，别的没问题

2022-05-07 10:03 UTC, linlinzzo commented
架构就不用删去了吧。

2022-05-14 13:42 UTC, linlinzzo commented
@OhYee @soxft

2022-05-16 13:41 UTC, soxft requested changes
~/utils/backend/database.ts Line:40 貌似应该为 `blog.arch`, 而不是`blog.string`

2022-05-16 16:58 UTC, OhYee requested changes
需要修改内容

2022-05-16 16:58 UTC, OhYee commented on pages/manager/index.tsx
> -      key: 'arch',
保留架构

2022-05-16 16:58 UTC, OhYee commented on utils/backend/database.ts
> -          arch: shouldString(blog.arch, ""),
拼写错误

2022-05-17 09:06 UTC, OhYee approved these changes

2022-05-17 09:11 UTC, soxft approved these changes

2022-05-17 09:11 UTC, merged